<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{7e27becc-e490-40b6-aafc-d0fb9b2b9f74}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbMotionTstLab: FB_MotionStage;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Run fb Motion Stage
fbMotionTstLab(stMotionStage:=GVL_Devices.M1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>